from os.path import join
from scripts.config import SOURCEDATA

SOURCEDATA_FLORIN = join(SOURCEDATA, 'BIDS_Florin_MEG_LFP')

#%% Subject Info
FLORIN_SUBJECT_MAP = {'S001': 'FloML001',
                      'S002': 'FloML002',
                      'S003': 'FloML003',
                      'S004': 'FloML004',
                      'S008': 'FloML005',
                      'S009': 'FloML006',
                      'S010': 'FloML007',
                      'S011': 'FloML008',
                      'S012': 'FloML009',
                      'S013': 'FloML010',
                      'S014': 'FloML011',
                      'S016': 'FloML012',
                      'S020': 'FloML013',
                      'S021': 'FloML014',
                      'S022': 'FloML015',
                      'S023': 'FloML016',
                      'S025': 'FloML017',
                      'S027': 'FloML018',
                      'S028': 'FloML019',
                      'S029': 'FloML020',
                      'S032': 'FloML021',
                      'S033': 'FloML022',
                      'S034': 'FloML023',
                      'S036': 'FloML024',
                      'S037': 'FloML025',
                      'S038': 'FloML026',
                      'S041': 'FloML027',
                      'S043': 'FloML028'}
FLORIN_SUBJECT_MAP_REV = {v: k for k, v in FLORIN_SUBJECT_MAP.items()}

FLORIN_CHNAME_MAP_BOSTON = {'EEG001': 'LFP_R_1_STN_BS',
                            'EEG002': 'LFP_R_2a_STN_BS',
                            'EEG003': 'LFP_R_2b_STN_BS',
                            'EEG004': 'LFP_R_2c_STN_BS',
                            'EEG005': 'LFP_R_3a_STN_BS',
                            'EEG006': 'LFP_R_3b_STN_BS',
                            'EEG007': 'LFP_R_3c_STN_BS',
                            'EEG008': 'LFP_R_4_STN_BS',

                            'EEG033': 'LFP_L_1_STN_BS',
                            'EEG034': 'LFP_L_2a_STN_BS',
                            'EEG035': 'LFP_L_2b_STN_BS',
                            'EEG036': 'LFP_L_2c_STN_BS',
                            'EEG037': 'LFP_L_3a_STN_BS',
                            'EEG038': 'LFP_L_3b_STN_BS',
                            'EEG039': 'LFP_L_3c_STN_BS',
                            'EEG040': 'LFP_L_4_STN_BS'}

FLORIN_CHNAME_MAP_STJUDE = {'EEG001': 'LFP_R_1_STN_SJ',
                            'EEG002': 'LFP_R_2a_STN_SJ',
                            'EEG003': 'LFP_R_3a_STN_SJ',
                            'EEG004': 'LFP_R_2b_STN_SJ',
                            'EEG005': 'LFP_R_4_STN_SJ',
                            'EEG006': 'LFP_R_3b_STN_SJ',
                            'EEG007': 'LFP_R_2c_STN_SJ',
                            'EEG008': 'LFP_R_3c_STN_SJ',

                            'EEG033': 'LFP_L_1_STN_SJ',
                            'EEG034': 'LFP_L_2a_STN_SJ',
                            'EEG035': 'LFP_L_3a_STN_SJ',
                            'EEG036': 'LFP_L_2b_STN_SJ',
                            'EEG037': 'LFP_L_4_STN_SJ',
                            'EEG038': 'LFP_L_3b_STN_SJ',
                            'EEG039': 'LFP_L_2c_STN_SJ',
                            'EEG040': 'LFP_L_3c_STN_SJ'}

FLORIN_CHNAME_MAP_EMPTY = {'EEG001': 'Amp_R_1',
                           'EEG002': 'Amp_R_2a',
                           'EEG003': 'Amp_R_3a',
                           'EEG004': 'Amp_R_2b',
                           'EEG005': 'Amp_R_4',
                           'EEG006': 'Amp_R_3b',
                           'EEG007': 'Amp_R_2c',
                           'EEG008': 'Amp_R_3c',

                           'EEG009': 'Amp_L_1',
                           'EEG010': 'Amp_L_2a',
                           'EEG011': 'Amp_L_2b',
                           'EEG012': 'Amp_L_2c',
                           'EEG013': 'Amp_L_3a',
                           'EEG014': 'Amp_L_3b',
                           'EEG015': 'Amp_L_3c',
                           'EEG016': 'Amp_L_4'}

FLORIN_DAYS_RECORDING = {'S001': 1,
                         'S002': 1,
                         'S003': 1,
                         'S004': 1,
                         'S008': 4,
                         'S009': 4,
                         'S010': 1,
                         'S011': 1,
                         'S012': 2,
                         'S013': 1,
                         'S014': 1,
                         'S016': 1,
                         'S020': 1,
                         'S021': 1,
                         'S022': 1,
                         'S023': 1,
                         'S025': 1,
                         'S027': 2,
                         'S028': 1,
                         'S029': 1,
                         'S032': 3,
                         'S033': 3,
                         'S034': 1,
                         'S036': 1,
                         'S037': 1,
                         'S038': 1,
                         'S041': 1,
                         'S043': 1}

#%% BIDS meta data
FLORIN_META = dict(
        name="BIDS_Florin_MEG_LFP",
        dataset_type="raw",
        data_license="CC Attribution-ShareAlike (CC BY-SA)",
        authors=['Florin, E.', 'Schnitzler, A.', 'Sure, M.'],
        how_to_acknowledge="n/a",
        references_and_links=[],
        acknowledgements=None,
        funding=None,
        doi='https://doi.org/10.5287/bodleian:mzJ7YwXvo')
