from .figure1 import figure1
from .figure2 import figure2
from .figure3 import figure3
from .figure4 import figure4
from .figure5 import figure5
from .figure6 import figure6
from .figure7 import figure7
from .figure8 import figure8
from .supp_figure1 import supp_figure1
from .supp_figure2 import supp_figure2
from .supp_figure3 import supp_figure3
from .supp_figure4 import supp_figure4
from .supp_figure5 import supp_figure5
from .supp_figure6 import supp_figure6
from .supp_figure7 import supp_figure7
from .supp_figure8 import supp_figure8
